// webpack-rust-svelte-tw/src/App.svelte
<script>
  import { onMount } from "svelte";

  const greeting = "Webpack + Rust + Svelte + Tailwind";

  onMount(async () => {
    const { greet } = await import("../pkg");
    greet();
  });
</script>

<style lang="postcss">
  .custom-style {
    @apply text-red-600 text-2xl my-4;
  }
</style>

<div class="flex flex-col justify-center items-center min-h-screen">
  <h1 class="custom-style">{greeting}</h1>
  <p>Edit <code class="text-red-800">src/App.svelte</code> to start</p>
</div>

// preact-ts-tw/src/components/App.tsx
import { h, FunctionalComponent } from "preact";

const App: FunctionalComponent = () => {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center">
      <h1 className="text-purple-700">Preact CLI + TypeScript + Tailwind</h1>
      <p className="mt-4">
        Edit <code className="text-pink-700">src/components/App.tsx</code> to
        start
      </p>
    </div>
  );
};

export default App;
